[package]
name = "HaneulSystem"
version = "0.0.1"
published-at = "0x3"
edition = "2024.beta"

[dependencies]
MoveStdlib = { local = "../move-stdlib" }
Haneul = { local = "../haneul-framework" }

[addresses]
haneul_system = "0x3"
