[package]
name = "perpetuals_orders"
edition = "2024"

[dependencies]
Haneul = { local = "../../deps/haneul-src/crates/haneul-framework/packages/haneul-framework" }
MoveStdlib = { local = "../../deps/haneul-src/crates/haneul-framework/packages/move-stdlib" }
perpetuals = { local = "../perpetuals" }
authority_cap = { local = "../authority_cap" }
oracle_aggregator = { local = "../oracle_aggregator" }
ifixed = { local = "../ifixed" }

[addresses]
perpetuals_orders = "0x0"
